name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    container:
      image: node:20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          node-version: 20

      - name: Install backend dependencies
        run: npm ci
        working-directory: backend

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          run: npm ci
          build: npm run build
          start: npm run test:mode

        env:
          CYPRESS_REACT_APP_TEST_API_URL: http://localhost:5001
          CYPRESS_REACT_APP_BASE_URL: http://localhost:3000
          REACT_APP_TEST_API_URL: http://localhost:5001
          REACT_APP_BASE_URL: http://localhost:3000
