name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    name: Build and test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install backend dependencies
        run: npm ci
        working-directory: backend

      - name: Install frontend dependencies
        run: npm install --legacy-peer-deps
        working-directory: frontend

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          install: false
          start: npm run test:mode
          wait-on: "http://localhost:3000"
        env:
          REACT_APP_TEST_API_URL: http://localhost:5001
          REACT_APP_BASE_URL: http://localhost:3000
          TOKEN: ZFz5iL6c8hdlyU0aV83PdZxhEpHO8l61hv
          REFRESH_TOKEN: 6YL6javjBVpuh82CYUEPNNYJhm7rhyBb
          TOKEN_EXPIRY: 1d
          REFRESH_TOKEN_EXPIRY: 7d
          REACT_APP_FIREBASE_API_KEY: AIzaSyDOJLrUYc3oF7UlS92flVThmrGvgJ8amNI
          REACT_APP_FIREBASE_AUTH_DOMAIN: mycash-bbb37.firebaseapp.com
          REACT_APP_FIREBASE_PROJECT_ID: mycash-bbb37
          REACT_APP_FIREBASE_STORAGE_BUCKET: mycash-bbb37.appspot.com
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: 741088509128
          REACT_APP_FIREBASE_APP_ID: 1:741088509128:web:69dce1177516731cbb39fd
