name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Echo REACT_APP_TEST_API_URL
        run: echo "REACT_APP_TEST_API_URL is ${{ secrets.REACT_APP_TEST_API_URL }}"

      # - name: Checkout
      #   uses: actions/checkout@v4

      # - name: Install frontend dependencies
      #   working-directory: frontend
      #   run: npm install --legacy-peer-deps

      # - name: Install backend dependencies
      #   working-directory: backend
      #   run: npm install

      # - name: Cypress run
      #   uses: cypress-io/github-action@v6
      #   with:
      #     working-directory: frontend
      #     install: false # Skip installation as we've already done it
      #     build: npm run build
      #     start: npm run test:mode
      #     wait-on: "http://localhost:3000"
