name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    env:
      MONGO_TEST_URL: ${{ secrets.MONGO_TEST_URL }}
      TOKEN: ${{ secrets.TOKEN }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      TOKEN_EXPIRY: ${{ secrets.TOKEN_EXPIRY }}
      REACT_APP_TEST_EMAIL: ${{ secrets.REACT_APP_TEST_EMAIL }}
      REACT_APP_TEST_PASSWORD: ${{ secrets.REACT_APP_TEST_PASSWORD }}
      REACT_APP_TEST_API_URL: ${{ secrets.REACT_APP_TEST_API_URL }}
      REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
      REACT_APP_CLOUDINARY_NAME: ${{ secrets.REACT_APP_CLOUDINARY_NAME }}
      REACT_APP_CLOUDINARY_API_KEY: ${{ secrets.REACT_APP_CLOUDINARY_API_KEY }}
      REACT_APP_CLOUDINARY_API_SECRET: ${{ secrets.REACT_APP_CLOUDINARY_API_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install --legacy-peer-deps

      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          install: false # Skip installation as we've already done it
          build: npm run build
          start: npm run test:mode
